Algoritmo "TABUADA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2023
Var

   num, i: inteiro

Inicio

   escreva("Digite um número:")
   leia(num)

   para i de 1 ate 10 passo 1 faca
      escreval(num, " x ",i, " = ", num * i)
   fimpara


Fimalgoritmo